project:
  type: website

website:
  favicon: "images/brain.jpg"
  navbar:
    background: primary
    left:
      - text: "Luke Slipski"
        href: index.qmd
    right:
      - writing.qmd
      - music.qmd
      - power_hours.qmd
  page-footer: "Proudly Maintained by Dunce Analytics" 

format:
  html:
    theme: 
      light: vapor
    css: styles.css
    toc: true

editor: source

