---
title: "The Overnight Lows"
format: html
about:
  id: hero-heading
  template: marquee
---

Luke Slipski and the Overnight Lows hail from Ohio, California, Colorado, New York, and regrettably, New Hampshire. Their contrived blend of alt rock and pop boppers cast in the form, but with none of the function, of broadway power ballads clash tragically with attempts to incorporate elements of classical tenor saxophone. Come to hear the eponymous Luke Slipski (singer/songwriter/producer) serve up predictable, though at times maladroit, melodies that leave you curious. Stay to hear The Overnight Lows (drums, vocals, piano, guitar) drop some chilly sounds admittedly worth hearing. You may find yourself with their brainworms stuck deep in your head while you reach for something a bit more listenable.

\
\

## Sun Summoner EP

<iframe style="border: 0; 
width: 350px; 
height: 621px;" src="https://bandcamp.com/EmbeddedPlayer/album=2824884446/size=large/bgcol=333333/linkcol=9a64ff/transparent=true/" seamless><a href="https://lukeslipskiandtheovernightlows.bandcamp.com/album/sun-summoner-ep">Sun Summoner EP by Luke Slipski and the Overnight Lows</a></iframe>


## Fantaisie
<iframe 
style="border: 0; width: 350px; height: 555px;" src="https://bandcamp.com/EmbeddedPlayer/album=3172649294/size=large/bgcol=333333/linkcol=9a64ff/transparent=true/" seamless>
<a href="https://lukeslipskiandtheovernightlows.bandcamp.com/album/fantaisie">Fantaisie by Luke Slipski and the Overnight Lows</a>
</iframe>
